# **Tuberculosis Classifier**

I have build a machine learning model that classifies TB using images. I have used this data [https://www.kaggle.com/tawsifurrahman/tuberculosis-tb-chest-xray-dataset](https://www.kaggle.com/tawsifurrahman/tuberculosis-tb-chest-xray-dataset)

## **Loading Necessary Libraries.**

In [42]:
import numpy  as np
import pandas as pd
from skimage.transform import resize
from skimage.io import imread
import matplotlib.pyplot as plt
import os
import seaborn as sns

## Converting images into numpy array and then loading it into a dataframe

In [2]:
Root_dir='/content/drive/MyDrive/TB_Chest_Radiography_Database'

In [3]:
Categories=['Normal', 'Tuberculosis']
feature_arr=[]
labels_arr=[]

In [7]:
for i in Categories:
  path=os.path.join(Root_dir, i)
  for img in os.listdir(path):
    img_array=imread(os.path.join(path, img))
    img_resize=resize(img_array,(150,150,3))
    feature_arr.append(img_resize.flatten())
    labels_arr.append(Categories.index(i))
  print('Loading done')

Loading done
Loading done

In [8]:
flat_features=np.array(feature_arr)
labels=np.array(labels_arr)

In [11]:
df = pd.DataFrame(flat_features)
df["Label"] = labels

In [13]:
df.head()

          0         1         2         3  ...     67497     67498     67499  Label
0  0.431828  0.431828  0.431828  0.190980  ...  0.890876  0.890876  0.890876      0
1  0.028978  0.028978  0.028978  0.001182  ...  0.784314  0.784314  0.784314      0
2  0.750332  0.750332  0.750332  0.685537  ...  0.023529  0.023529  0.023529      0
3  0.053690  0.053690  0.053690  0.024340  ...  0.770677  0.770677  0.770677      0
4  0.019608  0.019608  0.019608  0.019608  ...  0.768209  0.768209  0.768209      0

[5 rows x 67501 columns]

In [15]:
final_features=df.drop(['Label'], axis='columns')

In [17]:
final_features.head()

      0         1         2      ...     67497     67498     67499
0  0.431828  0.431828  0.431828  ...  0.890876  0.890876  0.890876
1  0.028978  0.028978  0.028978  ...  0.784314  0.784314  0.784314
2  0.750332  0.750332  0.750332  ...  0.023529  0.023529  0.023529
3  0.053690  0.053690  0.053690  ...  0.770677  0.770677  0.770677
4  0.019608  0.019608  0.019608  ...  0.768209  0.768209  0.768209

[5 rows x 67500 columns]

In [20]:
final_labels=df[['Label']]

In [21]:
final_labels.head()

   Label
0      0
1      0
2      0
3      0
4      0

## Building Machine Learning Models

I have used 3 machine learning models.
1. KNN had an accuracy of 94%.
2. Decision Trees had an accuracy of 94%.
3. RandomForest Classifer had the best accuracy of 98%.

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train,y_test=train_test_split(final_features, final_labels, train_size=0.7)

In [24]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2940, 67500)
(1260, 67500)
(2940, 1)
(1260, 1)

In [37]:
KNN=KNeighborsClassifier()

In [26]:
KNN_model=KNN.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [28]:
print(f" KNN  ACCURACY {KNN_model.score(x_test,y_test)}")

 KNN  ACCURACY 0.9492063492063492

In [40]:
KNN_predic=KNN_model.predict(x_test)

In [57]:
Tree = DecisionTreeClassifier()
Tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [51]:
print(f" Decision Tree accuracy {Tree.score(x_test,y_test)}")

 Decision Tree accuracy 0.9484126984126984

In [52]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

RandomForestClassifier()

In [54]:
print(f"Random Forest accuracy : {rf.score(x_test,y_test)}")

Random Forest accuracy : 0.9817460317460317

In [55]:
best_predict=rf.predict(x_test)

In [56]:
best_predict

array([1, 0, 0, ..., 0, 0, 0])